// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: proto/media/v1/media.proto

package mediav1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MediaKind int32

const (
	MediaKind_KIND_UNSPECIFIED MediaKind = 0
	MediaKind_IMAGE            MediaKind = 1
	MediaKind_VIDEO            MediaKind = 2
	MediaKind_AUDIO            MediaKind = 3
)

// Enum value maps for MediaKind.
var (
	MediaKind_name = map[int32]string{
		0: "KIND_UNSPECIFIED",
		1: "IMAGE",
		2: "VIDEO",
		3: "AUDIO",
	}
	MediaKind_value = map[string]int32{
		"KIND_UNSPECIFIED": 0,
		"IMAGE":            1,
		"VIDEO":            2,
		"AUDIO":            3,
	}
)

func (x MediaKind) Enum() *MediaKind {
	p := new(MediaKind)
	*p = x
	return p
}

func (x MediaKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MediaKind) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_media_v1_media_proto_enumTypes[0].Descriptor()
}

func (MediaKind) Type() protoreflect.EnumType {
	return &file_proto_media_v1_media_proto_enumTypes[0]
}

func (x MediaKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MediaKind.Descriptor instead.
func (MediaKind) EnumDescriptor() ([]byte, []int) {
	return file_proto_media_v1_media_proto_rawDescGZIP(), []int{0}
}

type MediaStatus int32

const (
	MediaStatus_STATUS_UNSPECIFIED MediaStatus = 0
	MediaStatus_STORED             MediaStatus = 1
	MediaStatus_PROCESSING         MediaStatus = 2
	MediaStatus_READY              MediaStatus = 3
	MediaStatus_FAILED             MediaStatus = 4
	MediaStatus_DELETING           MediaStatus = 5
)

// Enum value maps for MediaStatus.
var (
	MediaStatus_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STORED",
		2: "PROCESSING",
		3: "READY",
		4: "FAILED",
		5: "DELETING",
	}
	MediaStatus_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STORED":             1,
		"PROCESSING":         2,
		"READY":              3,
		"FAILED":             4,
		"DELETING":           5,
	}
)

func (x MediaStatus) Enum() *MediaStatus {
	p := new(MediaStatus)
	*p = x
	return p
}

func (x MediaStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MediaStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_media_v1_media_proto_enumTypes[1].Descriptor()
}

func (MediaStatus) Type() protoreflect.EnumType {
	return &file_proto_media_v1_media_proto_enumTypes[1]
}

func (x MediaStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MediaStatus.Descriptor instead.
func (MediaStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_media_v1_media_proto_rawDescGZIP(), []int{1}
}

type UploadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*UploadRequest_Init
	//	*UploadRequest_Chunk
	Payload       isUploadRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadRequest) Reset() {
	*x = UploadRequest{}
	mi := &file_proto_media_v1_media_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadRequest) ProtoMessage() {}

func (x *UploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_v1_media_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadRequest.ProtoReflect.Descriptor instead.
func (*UploadRequest) Descriptor() ([]byte, []int) {
	return file_proto_media_v1_media_proto_rawDescGZIP(), []int{0}
}

func (x *UploadRequest) GetPayload() isUploadRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *UploadRequest) GetInit() *UploadInit {
	if x != nil {
		if x, ok := x.Payload.(*UploadRequest_Init); ok {
			return x.Init
		}
	}
	return nil
}

func (x *UploadRequest) GetChunk() []byte {
	if x != nil {
		if x, ok := x.Payload.(*UploadRequest_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isUploadRequest_Payload interface {
	isUploadRequest_Payload()
}

type UploadRequest_Init struct {
	Init *UploadInit `protobuf:"bytes,1,opt,name=init,proto3,oneof"`
}

type UploadRequest_Chunk struct {
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*UploadRequest_Init) isUploadRequest_Payload() {}

func (*UploadRequest_Chunk) isUploadRequest_Payload() {}

type UploadInit struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OwnerId        string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Filename       string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	Mime           string                 `protobuf:"bytes,3,opt,name=mime,proto3" json:"mime,omitempty"`
	ExpectedSize   uint64                 `protobuf:"varint,4,opt,name=expected_size,json=expectedSize,proto3" json:"expected_size,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,5,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Processing     *ProcessingOptions     `protobuf:"bytes,6,opt,name=processing,proto3" json:"processing,omitempty"`
	Ttl            *durationpb.Duration   `protobuf:"bytes,7,opt,name=ttl,proto3" json:"ttl,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UploadInit) Reset() {
	*x = UploadInit{}
	mi := &file_proto_media_v1_media_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadInit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadInit) ProtoMessage() {}

func (x *UploadInit) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_v1_media_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadInit.ProtoReflect.Descriptor instead.
func (*UploadInit) Descriptor() ([]byte, []int) {
	return file_proto_media_v1_media_proto_rawDescGZIP(), []int{1}
}

func (x *UploadInit) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *UploadInit) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *UploadInit) GetMime() string {
	if x != nil {
		return x.Mime
	}
	return ""
}

func (x *UploadInit) GetExpectedSize() uint64 {
	if x != nil {
		return x.ExpectedSize
	}
	return 0
}

func (x *UploadInit) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *UploadInit) GetProcessing() *ProcessingOptions {
	if x != nil {
		return x.Processing
	}
	return nil
}

func (x *UploadInit) GetTtl() *durationpb.Duration {
	if x != nil {
		return x.Ttl
	}
	return nil
}

type ProcessingOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MakeThumbnail bool                   `protobuf:"varint,1,opt,name=make_thumbnail,json=makeThumbnail,proto3" json:"make_thumbnail,omitempty"`
	Transcode     bool                   `protobuf:"varint,2,opt,name=transcode,proto3" json:"transcode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessingOptions) Reset() {
	*x = ProcessingOptions{}
	mi := &file_proto_media_v1_media_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessingOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessingOptions) ProtoMessage() {}

func (x *ProcessingOptions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_v1_media_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessingOptions.ProtoReflect.Descriptor instead.
func (*ProcessingOptions) Descriptor() ([]byte, []int) {
	return file_proto_media_v1_media_proto_rawDescGZIP(), []int{2}
}

func (x *ProcessingOptions) GetMakeThumbnail() bool {
	if x != nil {
		return x.MakeThumbnail
	}
	return false
}

func (x *ProcessingOptions) GetTranscode() bool {
	if x != nil {
		return x.Transcode
	}
	return false
}

type UploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       string                 `protobuf:"bytes,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	Status        MediaStatus            `protobuf:"varint,2,opt,name=status,proto3,enum=media.v1.MediaStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadResponse) Reset() {
	*x = UploadResponse{}
	mi := &file_proto_media_v1_media_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadResponse) ProtoMessage() {}

func (x *UploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_v1_media_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadResponse.ProtoReflect.Descriptor instead.
func (*UploadResponse) Descriptor() ([]byte, []int) {
	return file_proto_media_v1_media_proto_rawDescGZIP(), []int{3}
}

func (x *UploadResponse) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

func (x *UploadResponse) GetStatus() MediaStatus {
	if x != nil {
		return x.Status
	}
	return MediaStatus_STATUS_UNSPECIFIED
}

type Media struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerId       string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Kind          MediaKind              `protobuf:"varint,3,opt,name=kind,proto3,enum=media.v1.MediaKind" json:"kind,omitempty"`
	Mime          string                 `protobuf:"bytes,4,opt,name=mime,proto3" json:"mime,omitempty"`
	SizeBytes     uint64                 `protobuf:"varint,5,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Status        MediaStatus            `protobuf:"varint,6,opt,name=status,proto3,enum=media.v1.MediaStatus" json:"status,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,7,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Derivatives   []*Derivative          `protobuf:"bytes,8,rep,name=derivatives,proto3" json:"derivatives,omitempty"`
	Error         string                 `protobuf:"bytes,9,opt,name=error,proto3" json:"error,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Media) Reset() {
	*x = Media{}
	mi := &file_proto_media_v1_media_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Media) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Media) ProtoMessage() {}

func (x *Media) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_v1_media_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Media.ProtoReflect.Descriptor instead.
func (*Media) Descriptor() ([]byte, []int) {
	return file_proto_media_v1_media_proto_rawDescGZIP(), []int{4}
}

func (x *Media) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Media) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Media) GetKind() MediaKind {
	if x != nil {
		return x.Kind
	}
	return MediaKind_KIND_UNSPECIFIED
}

func (x *Media) GetMime() string {
	if x != nil {
		return x.Mime
	}
	return ""
}

func (x *Media) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *Media) GetStatus() MediaStatus {
	if x != nil {
		return x.Status
	}
	return MediaStatus_STATUS_UNSPECIFIED
}

func (x *Media) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Media) GetDerivatives() []*Derivative {
	if x != nil {
		return x.Derivatives
	}
	return nil
}

func (x *Media) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Media) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type Derivative struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Variant       string                 `protobuf:"bytes,1,opt,name=variant,proto3" json:"variant,omitempty"`
	Mime          string                 `protobuf:"bytes,2,opt,name=mime,proto3" json:"mime,omitempty"`
	SizeBytes     uint64                 `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Derivative) Reset() {
	*x = Derivative{}
	mi := &file_proto_media_v1_media_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Derivative) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Derivative) ProtoMessage() {}

func (x *Derivative) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_v1_media_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Derivative.ProtoReflect.Descriptor instead.
func (*Derivative) Descriptor() ([]byte, []int) {
	return file_proto_media_v1_media_proto_rawDescGZIP(), []int{5}
}

func (x *Derivative) GetVariant() string {
	if x != nil {
		return x.Variant
	}
	return ""
}

func (x *Derivative) GetMime() string {
	if x != nil {
		return x.Mime
	}
	return ""
}

func (x *Derivative) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

type GetMediaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       string                 `protobuf:"bytes,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMediaRequest) Reset() {
	*x = GetMediaRequest{}
	mi := &file_proto_media_v1_media_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMediaRequest) ProtoMessage() {}

func (x *GetMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_v1_media_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMediaRequest.ProtoReflect.Descriptor instead.
func (*GetMediaRequest) Descriptor() ([]byte, []int) {
	return file_proto_media_v1_media_proto_rawDescGZIP(), []int{6}
}

func (x *GetMediaRequest) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

type ListMediaByOwnerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	PageSize      uint32                 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMediaByOwnerRequest) Reset() {
	*x = ListMediaByOwnerRequest{}
	mi := &file_proto_media_v1_media_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMediaByOwnerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMediaByOwnerRequest) ProtoMessage() {}

func (x *ListMediaByOwnerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_v1_media_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMediaByOwnerRequest.ProtoReflect.Descriptor instead.
func (*ListMediaByOwnerRequest) Descriptor() ([]byte, []int) {
	return file_proto_media_v1_media_proto_rawDescGZIP(), []int{7}
}

func (x *ListMediaByOwnerRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *ListMediaByOwnerRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListMediaByOwnerRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListMediaByOwnerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Media               `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMediaByOwnerResponse) Reset() {
	*x = ListMediaByOwnerResponse{}
	mi := &file_proto_media_v1_media_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMediaByOwnerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMediaByOwnerResponse) ProtoMessage() {}

func (x *ListMediaByOwnerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_v1_media_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMediaByOwnerResponse.ProtoReflect.Descriptor instead.
func (*ListMediaByOwnerResponse) Descriptor() ([]byte, []int) {
	return file_proto_media_v1_media_proto_rawDescGZIP(), []int{8}
}

func (x *ListMediaByOwnerResponse) GetItems() []*Media {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListMediaByOwnerResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type GetDownloadURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       string                 `protobuf:"bytes,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	Variant       string                 `protobuf:"bytes,2,opt,name=variant,proto3" json:"variant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDownloadURLRequest) Reset() {
	*x = GetDownloadURLRequest{}
	mi := &file_proto_media_v1_media_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDownloadURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDownloadURLRequest) ProtoMessage() {}

func (x *GetDownloadURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_v1_media_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDownloadURLRequest.ProtoReflect.Descriptor instead.
func (*GetDownloadURLRequest) Descriptor() ([]byte, []int) {
	return file_proto_media_v1_media_proto_rawDescGZIP(), []int{9}
}

func (x *GetDownloadURLRequest) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

func (x *GetDownloadURLRequest) GetVariant() string {
	if x != nil {
		return x.Variant
	}
	return ""
}

type GetDownloadURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDownloadURLResponse) Reset() {
	*x = GetDownloadURLResponse{}
	mi := &file_proto_media_v1_media_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDownloadURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDownloadURLResponse) ProtoMessage() {}

func (x *GetDownloadURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_v1_media_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDownloadURLResponse.ProtoReflect.Descriptor instead.
func (*GetDownloadURLResponse) Descriptor() ([]byte, []int) {
	return file_proto_media_v1_media_proto_rawDescGZIP(), []int{10}
}

func (x *GetDownloadURLResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *GetDownloadURLResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type DownloadStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       string                 `protobuf:"bytes,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	Variant       string                 `protobuf:"bytes,2,opt,name=variant,proto3" json:"variant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadStreamRequest) Reset() {
	*x = DownloadStreamRequest{}
	mi := &file_proto_media_v1_media_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadStreamRequest) ProtoMessage() {}

func (x *DownloadStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_v1_media_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadStreamRequest.ProtoReflect.Descriptor instead.
func (*DownloadStreamRequest) Descriptor() ([]byte, []int) {
	return file_proto_media_v1_media_proto_rawDescGZIP(), []int{11}
}

func (x *DownloadStreamRequest) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

func (x *DownloadStreamRequest) GetVariant() string {
	if x != nil {
		return x.Variant
	}
	return ""
}

type DownloadChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadChunk) Reset() {
	*x = DownloadChunk{}
	mi := &file_proto_media_v1_media_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadChunk) ProtoMessage() {}

func (x *DownloadChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_v1_media_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadChunk.ProtoReflect.Descriptor instead.
func (*DownloadChunk) Descriptor() ([]byte, []int) {
	return file_proto_media_v1_media_proto_rawDescGZIP(), []int{12}
}

func (x *DownloadChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type DeleteMediaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       string                 `protobuf:"bytes,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMediaRequest) Reset() {
	*x = DeleteMediaRequest{}
	mi := &file_proto_media_v1_media_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMediaRequest) ProtoMessage() {}

func (x *DeleteMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_v1_media_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMediaRequest.ProtoReflect.Descriptor instead.
func (*DeleteMediaRequest) Descriptor() ([]byte, []int) {
	return file_proto_media_v1_media_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteMediaRequest) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

type DeleteMediaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       bool                   `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMediaResponse) Reset() {
	*x = DeleteMediaResponse{}
	mi := &file_proto_media_v1_media_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMediaResponse) ProtoMessage() {}

func (x *DeleteMediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_v1_media_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMediaResponse.ProtoReflect.Descriptor instead.
func (*DeleteMediaResponse) Descriptor() ([]byte, []int) {
	return file_proto_media_v1_media_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteMediaResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type DeleteByOwnerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteByOwnerRequest) Reset() {
	*x = DeleteByOwnerRequest{}
	mi := &file_proto_media_v1_media_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteByOwnerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteByOwnerRequest) ProtoMessage() {}

func (x *DeleteByOwnerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_v1_media_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteByOwnerRequest.ProtoReflect.Descriptor instead.
func (*DeleteByOwnerRequest) Descriptor() ([]byte, []int) {
	return file_proto_media_v1_media_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteByOwnerRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

type DeleteByOwnerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeletedCount  uint32                 `protobuf:"varint,1,opt,name=deleted_count,json=deletedCount,proto3" json:"deleted_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteByOwnerResponse) Reset() {
	*x = DeleteByOwnerResponse{}
	mi := &file_proto_media_v1_media_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteByOwnerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteByOwnerResponse) ProtoMessage() {}

func (x *DeleteByOwnerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_v1_media_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteByOwnerResponse.ProtoReflect.Descriptor instead.
func (*DeleteByOwnerResponse) Descriptor() ([]byte, []int) {
	return file_proto_media_v1_media_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteByOwnerResponse) GetDeletedCount() uint32 {
	if x != nil {
		return x.DeletedCount
	}
	return 0
}

var File_proto_media_v1_media_proto protoreflect.FileDescriptor

const file_proto_media_v1_media_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/media/v1/media.proto\x12\bmedia.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a!proto/buf/validate/validate.proto\"^\n" +
	"\rUploadRequest\x12*\n" +
	"\x04init\x18\x01 \x01(\v2\x14.media.v1.UploadInitH\x00R\x04init\x12\x16\n" +
	"\x05chunk\x18\x02 \x01(\fH\x00R\x05chunkB\t\n" +
	"\apayload\"\xbd\x02\n" +
	"\n" +
	"UploadInit\x12#\n" +
	"\bowner_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\aownerId\x12#\n" +
	"\bfilename\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\bfilename\x12\x1b\n" +
	"\x04mime\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04mime\x12,\n" +
	"\rexpected_size\x18\x04 \x01(\x04B\a\xbaH\x042\x02 \x00R\fexpectedSize\x120\n" +
	"\x0fidempotency_key\x18\x05 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x0eidempotencyKey\x12;\n" +
	"\n" +
	"processing\x18\x06 \x01(\v2\x1b.media.v1.ProcessingOptionsR\n" +
	"processing\x12+\n" +
	"\x03ttl\x18\a \x01(\v2\x19.google.protobuf.DurationR\x03ttl\"X\n" +
	"\x11ProcessingOptions\x12%\n" +
	"\x0emake_thumbnail\x18\x01 \x01(\bR\rmakeThumbnail\x12\x1c\n" +
	"\ttranscode\x18\x02 \x01(\bR\ttranscode\"Z\n" +
	"\x0eUploadResponse\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\tR\amediaId\x12-\n" +
	"\x06status\x18\x02 \x01(\x0e2\x15.media.v1.MediaStatusR\x06status\"\xfb\x02\n" +
	"\x05Media\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\x12'\n" +
	"\x04kind\x18\x03 \x01(\x0e2\x13.media.v1.MediaKindR\x04kind\x12\x12\n" +
	"\x04mime\x18\x04 \x01(\tR\x04mime\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x05 \x01(\x04R\tsizeBytes\x12-\n" +
	"\x06status\x18\x06 \x01(\x0e2\x15.media.v1.MediaStatusR\x06status\x123\n" +
	"\bmetadata\x18\a \x01(\v2\x17.google.protobuf.StructR\bmetadata\x126\n" +
	"\vderivatives\x18\b \x03(\v2\x14.media.v1.DerivativeR\vderivatives\x12\x14\n" +
	"\x05error\x18\t \x01(\tR\x05error\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"Y\n" +
	"\n" +
	"Derivative\x12\x18\n" +
	"\avariant\x18\x01 \x01(\tR\avariant\x12\x12\n" +
	"\x04mime\x18\x02 \x01(\tR\x04mime\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x04R\tsizeBytes\"6\n" +
	"\x0fGetMediaRequest\x12#\n" +
	"\bmedia_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\amediaId\"\x86\x01\n" +
	"\x17ListMediaByOwnerRequest\x12#\n" +
	"\bowner_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\aownerId\x12'\n" +
	"\tpage_size\x18\x02 \x01(\rB\n" +
	"\xbaH\a*\x05\x18\xe8\a \x00R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"i\n" +
	"\x18ListMediaByOwnerResponse\x12%\n" +
	"\x05items\x18\x01 \x03(\v2\x0f.media.v1.MediaR\x05items\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\x85\x01\n" +
	"\x15GetDownloadURLRequest\x12#\n" +
	"\bmedia_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\amediaId\x12G\n" +
	"\avariant\x18\x02 \x01(\tB-\xbaH*r(R\boriginalR\x05thumbR\x05r_720R\x05r_360R\apreviewR\avariant\"e\n" +
	"\x16GetDownloadURLResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x129\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\x85\x01\n" +
	"\x15DownloadStreamRequest\x12#\n" +
	"\bmedia_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\amediaId\x12G\n" +
	"\avariant\x18\x02 \x01(\tB-\xbaH*r(R\boriginalR\x05thumbR\x05r_720R\x05r_360R\apreviewR\avariant\"#\n" +
	"\rDownloadChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"9\n" +
	"\x12DeleteMediaRequest\x12#\n" +
	"\bmedia_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\amediaId\"/\n" +
	"\x13DeleteMediaResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted\";\n" +
	"\x14DeleteByOwnerRequest\x12#\n" +
	"\bowner_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\aownerId\"<\n" +
	"\x15DeleteByOwnerResponse\x12#\n" +
	"\rdeleted_count\x18\x01 \x01(\rR\fdeletedCount*B\n" +
	"\tMediaKind\x12\x14\n" +
	"\x10KIND_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05IMAGE\x10\x01\x12\t\n" +
	"\x05VIDEO\x10\x02\x12\t\n" +
	"\x05AUDIO\x10\x03*f\n" +
	"\vMediaStatus\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06STORED\x10\x01\x12\x0e\n" +
	"\n" +
	"PROCESSING\x10\x02\x12\t\n" +
	"\x05READY\x10\x03\x12\n" +
	"\n" +
	"\x06FAILED\x10\x04\x12\f\n" +
	"\bDELETING\x10\x052\xa1\x04\n" +
	"\fMediaService\x12=\n" +
	"\x06Upload\x12\x17.media.v1.UploadRequest\x1a\x18.media.v1.UploadResponse(\x01\x126\n" +
	"\bGetMedia\x12\x19.media.v1.GetMediaRequest\x1a\x0f.media.v1.Media\x12Y\n" +
	"\x10ListMediaByOwner\x12!.media.v1.ListMediaByOwnerRequest\x1a\".media.v1.ListMediaByOwnerResponse\x12S\n" +
	"\x0eGetDownloadURL\x12\x1f.media.v1.GetDownloadURLRequest\x1a .media.v1.GetDownloadURLResponse\x12L\n" +
	"\x0eDownloadStream\x12\x1f.media.v1.DownloadStreamRequest\x1a\x17.media.v1.DownloadChunk0\x01\x12J\n" +
	"\vDeleteMedia\x12\x1c.media.v1.DeleteMediaRequest\x1a\x1d.media.v1.DeleteMediaResponse\x12P\n" +
	"\rDeleteByOwner\x12\x1e.media.v1.DeleteByOwnerRequest\x1a\x1f.media.v1.DeleteByOwnerResponseB\x80\x01\n" +
	"\fcom.media.v1B\n" +
	"MediaProtoP\x01Z#mediaservice/proto/media/v1;mediav1\xa2\x02\x03MXX\xaa\x02\bMedia.V1\xca\x02\bMedia\\V1\xe2\x02\x14Media\\V1\\GPBMetadata\xea\x02\tMedia::V1b\x06proto3"

var (
	file_proto_media_v1_media_proto_rawDescOnce sync.Once
	file_proto_media_v1_media_proto_rawDescData []byte
)

func file_proto_media_v1_media_proto_rawDescGZIP() []byte {
	file_proto_media_v1_media_proto_rawDescOnce.Do(func() {
		file_proto_media_v1_media_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_media_v1_media_proto_rawDesc), len(file_proto_media_v1_media_proto_rawDesc)))
	})
	return file_proto_media_v1_media_proto_rawDescData
}

var file_proto_media_v1_media_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_media_v1_media_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_media_v1_media_proto_goTypes = []any{
	(MediaKind)(0),                   // 0: media.v1.MediaKind
	(MediaStatus)(0),                 // 1: media.v1.MediaStatus
	(*UploadRequest)(nil),            // 2: media.v1.UploadRequest
	(*UploadInit)(nil),               // 3: media.v1.UploadInit
	(*ProcessingOptions)(nil),        // 4: media.v1.ProcessingOptions
	(*UploadResponse)(nil),           // 5: media.v1.UploadResponse
	(*Media)(nil),                    // 6: media.v1.Media
	(*Derivative)(nil),               // 7: media.v1.Derivative
	(*GetMediaRequest)(nil),          // 8: media.v1.GetMediaRequest
	(*ListMediaByOwnerRequest)(nil),  // 9: media.v1.ListMediaByOwnerRequest
	(*ListMediaByOwnerResponse)(nil), // 10: media.v1.ListMediaByOwnerResponse
	(*GetDownloadURLRequest)(nil),    // 11: media.v1.GetDownloadURLRequest
	(*GetDownloadURLResponse)(nil),   // 12: media.v1.GetDownloadURLResponse
	(*DownloadStreamRequest)(nil),    // 13: media.v1.DownloadStreamRequest
	(*DownloadChunk)(nil),            // 14: media.v1.DownloadChunk
	(*DeleteMediaRequest)(nil),       // 15: media.v1.DeleteMediaRequest
	(*DeleteMediaResponse)(nil),      // 16: media.v1.DeleteMediaResponse
	(*DeleteByOwnerRequest)(nil),     // 17: media.v1.DeleteByOwnerRequest
	(*DeleteByOwnerResponse)(nil),    // 18: media.v1.DeleteByOwnerResponse
	(*durationpb.Duration)(nil),      // 19: google.protobuf.Duration
	(*structpb.Struct)(nil),          // 20: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),    // 21: google.protobuf.Timestamp
}
var file_proto_media_v1_media_proto_depIdxs = []int32{
	3,  // 0: media.v1.UploadRequest.init:type_name -> media.v1.UploadInit
	4,  // 1: media.v1.UploadInit.processing:type_name -> media.v1.ProcessingOptions
	19, // 2: media.v1.UploadInit.ttl:type_name -> google.protobuf.Duration
	1,  // 3: media.v1.UploadResponse.status:type_name -> media.v1.MediaStatus
	0,  // 4: media.v1.Media.kind:type_name -> media.v1.MediaKind
	1,  // 5: media.v1.Media.status:type_name -> media.v1.MediaStatus
	20, // 6: media.v1.Media.metadata:type_name -> google.protobuf.Struct
	7,  // 7: media.v1.Media.derivatives:type_name -> media.v1.Derivative
	21, // 8: media.v1.Media.created_at:type_name -> google.protobuf.Timestamp
	6,  // 9: media.v1.ListMediaByOwnerResponse.items:type_name -> media.v1.Media
	21, // 10: media.v1.GetDownloadURLResponse.expires_at:type_name -> google.protobuf.Timestamp
	2,  // 11: media.v1.MediaService.Upload:input_type -> media.v1.UploadRequest
	8,  // 12: media.v1.MediaService.GetMedia:input_type -> media.v1.GetMediaRequest
	9,  // 13: media.v1.MediaService.ListMediaByOwner:input_type -> media.v1.ListMediaByOwnerRequest
	11, // 14: media.v1.MediaService.GetDownloadURL:input_type -> media.v1.GetDownloadURLRequest
	13, // 15: media.v1.MediaService.DownloadStream:input_type -> media.v1.DownloadStreamRequest
	15, // 16: media.v1.MediaService.DeleteMedia:input_type -> media.v1.DeleteMediaRequest
	17, // 17: media.v1.MediaService.DeleteByOwner:input_type -> media.v1.DeleteByOwnerRequest
	5,  // 18: media.v1.MediaService.Upload:output_type -> media.v1.UploadResponse
	6,  // 19: media.v1.MediaService.GetMedia:output_type -> media.v1.Media
	10, // 20: media.v1.MediaService.ListMediaByOwner:output_type -> media.v1.ListMediaByOwnerResponse
	12, // 21: media.v1.MediaService.GetDownloadURL:output_type -> media.v1.GetDownloadURLResponse
	14, // 22: media.v1.MediaService.DownloadStream:output_type -> media.v1.DownloadChunk
	16, // 23: media.v1.MediaService.DeleteMedia:output_type -> media.v1.DeleteMediaResponse
	18, // 24: media.v1.MediaService.DeleteByOwner:output_type -> media.v1.DeleteByOwnerResponse
	18, // [18:25] is the sub-list for method output_type
	11, // [11:18] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_media_v1_media_proto_init() }
func file_proto_media_v1_media_proto_init() {
	if File_proto_media_v1_media_proto != nil {
		return
	}
	file_proto_media_v1_media_proto_msgTypes[0].OneofWrappers = []any{
		(*UploadRequest_Init)(nil),
		(*UploadRequest_Chunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_media_v1_media_proto_rawDesc), len(file_proto_media_v1_media_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_media_v1_media_proto_goTypes,
		DependencyIndexes: file_proto_media_v1_media_proto_depIdxs,
		EnumInfos:         file_proto_media_v1_media_proto_enumTypes,
		MessageInfos:      file_proto_media_v1_media_proto_msgTypes,
	}.Build()
	File_proto_media_v1_media_proto = out.File
	file_proto_media_v1_media_proto_goTypes = nil
	file_proto_media_v1_media_proto_depIdxs = nil
}
